#!/bin/bash

# setup.sh
# --------
# Install hdd-spindown.sh, generate a configuration for the rotating disks
# found in this system and enable the systemd service.
#
# Usage: ./setup.sh [-n]
#   -n  only print the configuration that would be generated
#
# Environment:
#   TIMEOUT  idle timeout in seconds for generated entries (default: 1800)
#   PREFIX   installation prefix (default: /usr)


readonly TIMEOUT="${TIMEOUT:-1800}"
readonly PREFIX="${PREFIX:-/usr}"
readonly CONFIG="/etc/hdd-spindown.rc"
SRC="$(dirname "$(readlink -f "$0")")"
readonly SRC


function disk_id() {
	# prefer stable ATA IDs, fall back to other by-id names
	for P in ata- wwn- scsi- usb-; do
		ID="$(find /dev/disk/by-id -lname "*/$1" -name "${P}*" 2>/dev/null | sort | head -n 1)"
		[ -n "$ID" ] && basename "$ID" && return 0
	done
	echo "$1"
}

function gen_config() {
	echo "# Configuration file for 'hdd-spindown.sh'"
	echo "# Generated by setup.sh on $(date '+%Y-%m-%d'), see hdd-spindown.rc for all options"
	echo
	echo "# Devices to be monitored: ATA-ID|timeout in seconds"
	DEVS=()
	for B in /sys/block/*; do
		DEV="$(basename "$B")"
		[ -e "$B/device" ] || continue
		MODEL="$(sed 's/ *$//' "$B/device/model" 2>/dev/null)"
		if [ "$(cat "$B/queue/rotational")" == "0" ]; then
			echo "#   skipped $DEV ($MODEL): SSD, no spindown needed"
			continue
		fi
		DEVS+=( "$(disk_id "$DEV")|$TIMEOUT" )
	done
	if [ ${#DEVS[@]} -eq 0 ]; then
		echo "#CONF_DEV=( )"
	else
		echo -n "CONF_DEV=( "
		for I in "${!DEVS[@]}"; do
			[ "$I" -gt 0 ] && echo -n "           "
			echo -n "'${DEVS[$I]}'"
			[ "$I" -lt $((${#DEVS[@]} - 1)) ] && echo " \\"
		done
		echo " )"
	fi
	cat <<'EOF'

# Monitoring interval in seconds
CONF_INT=300

# openSeaChest for Seagate drives (auto: models 'ST...')
CONF_SEACHEST=auto


# ---------------------------------------------------------------------------
# Status queries (comments only, NOT run by the script; paste into a shell)
# None of these commands wake up a drive in standby.
#
# Power state of all drives configured above:
#   hdd-spindown.sh status
#
# Service status / live log:
#   systemctl status hdd-spindown
#   journalctl -u hdd-spindown -f
#
# After changing this configuration:
#   systemctl restart hdd-spindown
EOF
}


if [ "$1" == "-n" ]; then
	gen_config
	exit 0
fi

if [ $EUID -ne 0 ]; then
	echo "error: setup.sh must be run as root" >&2
	exit 1
fi

# check prerequisites
FAIL=0
for CMD in hdparm smartctl systemctl; do
	which $CMD &>/dev/null && continue
	echo "error: missing '$CMD' executable in PATH" >&2
	FAIL=1
done
[ $FAIL -ne 0 ] && exit 1
which openSeaChest_PowerControl &>/dev/null || \
	echo "note: openSeaChest_PowerControl not found, Seagate drives will use smartctl/hdparm"

# install script and service unit
install -D -m 755 "$SRC/hdd-spindown.sh" "$PREFIX/bin/hdd-spindown.sh" || exit 1
install -D -m 644 "$SRC/hdd-spindown.service" \
	"$PREFIX/lib/systemd/system/hdd-spindown.service" || exit 1
echo "installed $PREFIX/bin/hdd-spindown.sh"

# generate configuration unless one exists
if [ -e "$CONFIG" ]; then
	echo "keeping existing $CONFIG (run './setup.sh -n' to see a generated one)"
else
	gen_config > "$CONFIG" || exit 1
	chmod 644 "$CONFIG"
	echo "generated $CONFIG"
fi

# enable and (re)start service
systemctl daemon-reload
systemctl enable hdd-spindown.service
systemctl restart hdd-spindown.service
systemctl is-active --quiet hdd-spindown.service || {
	echo "error: service failed to start, see 'journalctl -u hdd-spindown'" >&2
	exit 1
}
echo "service running"
echo
"$PREFIX/bin/hdd-spindown.sh" status
